version: "2"

run:
  go: "1.26"
  allow-parallel-runners: true
  timeout: 10m # Увеличил таймаут, так как линтеров очень много

linters:
  enable:
    # Все логические линтеры из вашего референса
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  mnd:
    ignored-numbers: ["24", "404", "200"] # Добавил типичные HTTP статусы
  revive:
    enable-all-rules: true
    rules:
      - name: exported
        disabled: true # Чтобы не писать комментарии к каждой функции на старте
      - name: package-comments
        disabled: true
  forbidigo:
    forbid:
      - '^(fmt\.Print(|f|ln)|print|println)$' # Запрет отладочного вывода

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/fancurson/go-secure-base)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0